# Generated by Django 5.0.7 on 2024-08-03 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="C",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="a",
            name="category",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="sample.c"
            ),
            preserve_default=False,
        ),
    ]
