# Generated by Django 5.0.7 on 2024-08-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0002_c_a_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atob",
            options={"ordering": ["order"]},
        ),
        migrations.AlterField(
            model_name="atob",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
