# Generated by Django 5.0.7 on 2024-08-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0003_alter_atob_options_alter_atob_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="atob",
            name="sort_order",
            field=models.IntegerField(blank=True, db_index=True, default=0),
            preserve_default=False,
        ),
    ]
